development:
  adapter: postgresql
  encoding: unicode
  database: runtip
  pool: 2
  username: root
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: root
  password:
