version: '3'

services:
  line-bot-app:
    tty: true
    container_name: api_container
    build: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - sqlite3

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/