version: '3'

services:
  line-bot-app:
    container_name: api_container
    build: 
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      env_file: .env
    depends_on:
      - line-bot-pgsql
    tty: true

  line-bot-pgsql:
    container_name: postgres_container
    build: 
      context: ./postgresql
    environment:
      PGDATA: /var/lib/postgresql/data/postgres-tipping
    volumes:
      - ./postgresql/work:/docker-entrypoint-initdb.d
      - runtip-data/:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    tty: true
    restart: always    

volumes:
  runtip-data: