version: '3'

services:
  line-bot-app:
    container_name: app_continer
    build: ./app_server
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - line-bot-postgres
    tty: true
  
  line-bot-postgres:
    container_name: postgres_container
    build: ./postgres_server
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: "line_api_user"
      POSTGRES_PASSWORD: "line_api_pass"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_server/sql/:/docker-entrypoint-initdb.d/
      - pgdata:/var/lib/postgresql/data/
    tty: true
    restart: always

volumes:
    pgdata: