version: '3'

services:
  line-bot-app:
    tty: true
    container_name: api_container
    build: ./app_server
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - sqlite3
  
  # line-bot-db:
  #   container_name: db_container
  #   build: ./mysql_server
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     env_file: .env
  #     TZ: Asia/Tokyo
  #   volumes:
  #     - mysql-data:/data/db
  #   ports:
  #     - 3306:3306
  #   restart: always
  #   tty: true

  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/